repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: compileall
        name: compileall
        entry: python -m compileall -q -x '.venv/|\.tmpl\.'
        language: system
        pass_filenames: false
