from typing import Protocol

from audio.backends.types import (
    BackendCapabilities,
    PlaybackSnapshot,
    AudioDiagnostics,
)


class AudioBackend(Protocol):
    """Common interface for all audio backends (GStreamer, MPD, etc.).

    UI talks to PlayerService; PlayerService talks to HybridAudioManager;
    HybridAudioManager delegates to the active AudioBackend.
    """

    backend_id: str
    capabilities: BackendCapabilities

    def play(self, path_or_uri: str) -> None: ...

    def pause(self) -> None: ...

    def resume(self) -> None: ...

    def toggle(self) -> None: ...

    def stop(self) -> None: ...

    def seek(self, seconds: float) -> None: ...

    def set_volume(self, volume: int) -> None: ...

    def set_queue(self, paths: list[str], start_index: int = 0) -> None: ...

    def enqueue(self, paths: list[str], play_now: bool = True) -> None: ...

    def enqueue_next(self, paths: list[str]) -> None: ...

    def clear_queue(self) -> None: ...

    def play_next(self) -> bool: ...

    def play_prev(self) -> bool: ...

    def get_queue(self) -> list[dict]: ...

    def get_queue_index(self) -> int: ...

    def get_snapshot(self) -> PlaybackSnapshot: ...

    def get_diagnostics(self) -> AudioDiagnostics: ...

    def shutdown(self) -> None: ...
