from __future__ import annotations

from typing import Protocol, runtime_checkable

from core.lyrics.models import (
    TrackIdentity, LyricsDocument, LyricsOperationResult,
    ProviderContract,
)


@runtime_checkable
class LyricsProvider(Protocol):
    @property
    def contract(self) -> ProviderContract: ...

    def resolve(self, identity: TrackIdentity,
                timeout_ms: int = 10000) -> LyricsOperationResult: ...

    def search(self, identity: TrackIdentity,
               timeout_ms: int = 10000) -> LyricsOperationResult: ...

    def close(self): ...


@runtime_checkable
class LyricsCacheRepository(Protocol):
    def get(self, cache_key: str) -> LyricsDocument | None: ...
    def put(self, cache_key: str, doc: LyricsDocument, ttl_s: int = 86400): ...
    def get_negative(self, cache_key: str) -> bool: ...
    def put_negative(self, cache_key: str, ttl_s: int = 3600): ...
    def invalidate(self, cache_key: str): ...
    def invalidate_all(self): ...
    def close(self): ...


@runtime_checkable
class EmbeddedLyricsReader(Protocol):
    def read(self, filepath: str) -> LyricsOperationResult: ...


@runtime_checkable
class EmbeddedLyricsWriter(Protocol):
    def write(self, filepath: str, doc: LyricsDocument) -> LyricsOperationResult: ...


@runtime_checkable
class SidecarProvider(Protocol):
    def read(self, directory: str, identity: TrackIdentity) -> LyricsOperationResult: ...
    def write(self, directory: str, doc: LyricsDocument) -> LyricsOperationResult: ...
    def delete(self, directory: str, identity: TrackIdentity) -> bool: ...


@runtime_checkable
class HttpTransport(Protocol):
    def get_json(self, url: str, headers: dict[str, str] | None = None,
                 timeout_ms: int = 10000) -> tuple[int, dict | list | None]: ...
    def close(self): ...
    def cancel(self): ...


@runtime_checkable
class Clock(Protocol):
    def now(self) -> str: ...


@runtime_checkable
class NetworkStatus(Protocol):
    @property
    def is_online(self) -> bool: ...
    def on_status_changed(self, callback: callable): ...
