from __future__ import annotations

from typing import Protocol, runtime_checkable

from core.radio.models import (
    Station, StationId, StationCreateRequest, StationUpdateRequest,
    PaginatedResult,
)


@runtime_checkable
class StationRepository(Protocol):
    def add(self, req: StationCreateRequest) -> Station: ...
    def get(self, station_id: StationId) -> Station | None: ...
    def update(self, station_id: StationId, req: StationUpdateRequest) -> Station | None: ...
    def delete(self, station_id: StationId) -> bool: ...
    def list_all(self, page: int = 1, page_size: int = 50) -> PaginatedResult: ...
    def search(self, query: str, page: int = 1, page_size: int = 50) -> PaginatedResult: ...
    def count(self) -> int: ...
    def set_favorite(self, station_id: StationId, favorite: bool) -> bool: ...
    def list_favorites(self, page: int = 1, page_size: int = 50) -> PaginatedResult: ...
    def find_by_url(self, url: str) -> Station | None: ...
    def mark_played(self, station_id: StationId): ...
    def list_recent(self, limit: int = 20) -> list[Station]: ...
    def update_probe(self, station_id: StationId, status: str, probe_at: str): ...
    def bulk_add(self, stations: list[StationCreateRequest], mode: str = "best_effort") -> int: ...
    def get_all_for_export(self) -> list[Station]: ...


@runtime_checkable
class RadioHistoryRepository(Protocol):
    def record_play(self, station_id: StationId, title: str = "", result: str = "", error_code: str = ""): ...
    def list_history(self, limit: int = 50, offset: int = 0) -> list[dict]: ...
    def count_history(self) -> int: ...
    def clear_history(self, retention_days: int | None = None): ...


@runtime_checkable
class HttpClient(Protocol):
    def request(self, method: str, url: str, headers: dict | None = None,
                timeout_ms: int = 10000, follow_redirects: bool = True,
                max_redirects: int = 5) -> tuple[int, bytes, dict[str, str]]: ...
    def close(self): ...


@runtime_checkable
class Clock(Protocol):
    def now(self) -> str: ...
    def utc_now(self) -> str: ...


@runtime_checkable
class Scheduler(Protocol):
    def schedule(self, delay_ms: int, callback: callable) -> object: ...
    def cancel(self, token: object): ...
    def close(self): ...


@runtime_checkable
class NetworkStatus(Protocol):
    @property
    def is_online(self) -> bool: ...
    def on_status_changed(self, callback: callable): ...


@runtime_checkable
class PlaybackBackend(Protocol):
    def play_url(self, url: str, headers: dict | None = None) -> bool: ...
    def stop(self): ...
    @property
    def is_playing(self) -> bool: ...
