"""Canonical mapping from QML context property names to BridgeFactory bridge keys."""
QML_CONTEXT_BINDINGS = {
    "appBridge": "app",
    "navigationBridge": "navigation",
    "themeBridge": "theme",
    "libraryBridge": "library",
    "michiAiBridge": "michi_ai",
    "metadataBridge": "metadata",
    "mixBridge": "mix",
    "playbackBridge": "playback",
    "nowplayingBridge": "nowplaying",
    "devicesBridge": "devices",
    "playlistsBridge": "playlists",
    "audioLabBridge": "audio_lab",
    "settingsBridge": "settings",
    "radioBridge": "radio",
    "connectionsBridge": "connections",
    "smartTaggingBridge": "smart_tagging",
    "libraryDoctorBridge": "library_doctor",
    "discLabBridge": "disc_lab",
    "selectionContextBridge": "selection_context",
    "homeAudioBridge": "home_audio",
    "lyricsBridge": "lyrics",
    "notificationBridge": "notification",
    "routeRegistryBridge": "route_registry",
    "appStateBridge": "app_state",
    "diagnosticsBridge": "diagnostics",
    "commandPaletteBridge": "command_palette",
    "actionRegistry": "action_registry",
    "globalSearchBridge": "global_search",
    "coverProviderBridge": "cover_provider",
    "jobBridge": "job_bridge",
    "desktopBridge": "desktop",
    "pageStateStore": "page_state",
}
