from __future__ import annotations

ROUTES: dict[str, dict] = {
    "home": {"title": "Inicio", "source": "../pages/home/HomePage.qml", "category": "core", "status": "functional"},
    "library.tracks": {"title": "Canciones", "source": "../pages/library/tracks/TracksPage.qml", "category": "library", "status": "functional"},
    "library.albums": {"title": "\u00c1lbumes", "source": "../pages/library/AlbumGridPage.qml", "category": "library", "status": "functional"},
    "library.album_detail": {"title": "\u00c1lbum", "source": "../pages/library/AlbumDetailPage.qml", "category": "detail", "status": "functional", "params": {"album_key": {"required": True, "type": "string"}}},
    "library.artists": {"title": "Artistas", "source": "../pages/library/ArtistGridPage.qml", "category": "library", "status": "functional"},
    "library.artist_detail": {"title": "Artista", "source": "../pages/library/ArtistDetailPage.qml", "category": "detail", "status": "functional", "params": {"artist": {"required": True, "type": "string"}}},
    "library.favorites": {"title": "Favoritos", "source": "../pages/library/FavoritesPage.qml", "category": "library", "status": "functional"},
    "library.recent": {"title": "Recientes", "source": "../pages/library/RecentPage.qml", "category": "library", "status": "functional"},
    "library.genres": {"title": "G\u00e9neros", "source": "../pages/library/GenresPage.qml", "category": "library", "status": "functional"},
    "library.folders": {"title": "Carpetas", "source": "../pages/library/FolderBrowserPage.qml", "category": "library", "status": "functional"},
    "library.folder_detail": {"title": "Carpeta", "source": "../pages/library/FolderBrowserPage.qml", "category": "detail", "status": "functional", "params": {"folder_id": {"required": True, "type": "string"}}},
    "library.sources": {"title": "Fuentes", "source": "../pages/library/SourcesPage.qml", "category": "library", "status": "functional"},
    "library.source_detail": {"title": "Detalle de fuente", "source": "../pages/library/SourceDetailPage.qml", "category": "detail", "status": "functional", "params": {"source_id": {"required": True, "type": "int"}}},
    "library.composers": {"title": "Compositores", "source": "../pages/library/ComposersPage.qml", "category": "library", "status": "functional"},
    "library.composer_detail": {"title": "Compositor", "source": "../pages/library/ComposerDetailPage.qml", "category": "detail", "status": "functional", "params": {"composer": {"required": True, "type": "string"}}},
    "library.years": {"title": "A\u00f1os", "source": "../pages/library/YearsPage.qml", "category": "library", "status": "functional"},
    "library.most_played": {"title": "M\u00e1s reproducidas", "source": "../pages/library/MostPlayedPage.qml", "category": "library", "status": "functional"},
    "library.unplayed": {"title": "Sin reproducir", "source": "../pages/library/UnplayedPage.qml", "category": "library", "status": "functional"},
    "library.missing": {"title": "Archivos faltantes", "source": "../pages/library/MissingPage.qml", "category": "library", "status": "functional"},
    "library.genre_detail": {"title": "G\u00e9nero", "source": "../pages/library/GenreDetailPage.qml", "category": "detail", "status": "functional", "params": {"genre": {"required": True, "type": "string"}}},
    "queue": {"title": "Cola", "source": "../pages/queue/QueuePage.qml", "category": "core", "status": "functional"},
    "playlists": {"title": "Playlists", "source": "../pages/playlists/PlaylistsPage.qml", "category": "core", "status": "functional"},
    "playlist_detail": {"title": "Playlist", "source": "../pages/playlists/PlaylistDetailPage.qml", "category": "detail", "status": "functional", "params": {"playlist_id": {"required": True, "type": "int"}}},
    "history": {"title": "Historial", "source": "../pages/history/HistoryPage.qml", "category": "core", "status": "functional"},
    "mix": {"title": "Mix", "source": "../pages/mix/MixHubPage.qml", "category": "core", "status": "functional"},
    "mix_detail": {"title": "Mix", "source": "../pages/mix/MixDetailPage.qml", "category": "detail", "status": "functional", "params": {"mix_id": {"required": True, "type": "string"}}},
    "mix_generator": {"title": "Generar Mix", "source": "../pages/mix/MixGeneratorPage.qml", "category": "detail", "status": "functional"},
    "mix_result": {"title": "Resultado Mix", "source": "../pages/mix/MixResultPage.qml", "category": "detail", "status": "functional"},
    "mix_rule_editor": {"title": "Editor de Reglas", "source": "../pages/mix/MixRuleEditorPage.qml", "category": "detail", "status": "functional"},
    "search": {"title": "Bsqueda", "source": "../pages/search/GlobalSearchPage.qml", "category": "core", "status": "functional"},
    "radio": {"title": "Radio", "source": "../pages/RadioPage.qml", "category": "core", "status": "functional"},
    "lyrics": {"title": "Letra", "source": "../pages/LyricsPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.overview": {"title": "Audio Lab", "source": "../pages/audio_lab/AudioLabOverviewPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.analysis": {"title": "Anlisis", "source": "../pages/audio_lab/AudioAnalysisPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.conversion": {"title": "Conversin", "source": "../pages/audio_lab/AudioConversionPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.normalization": {"title": "Normalizacin", "source": "../pages/audio_lab/AudioNormalizationPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.replaygain": {"title": "ReplayGain", "source": "../pages/audio_lab/ReplayGainPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.integrity": {"title": "Integridad", "source": "../pages/audio_lab/AudioIntegrityPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.comparison": {"title": "Comparacin", "source": "../pages/audio_lab/AudioComparisonPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.jobs": {"title": "Trabajos", "source": "../pages/audio_lab/AudioBatchJobsPage.qml", "category": "tools", "status": "functional"},
    "audio_lab.profiles": {"title": "Perfiles", "source": "../pages/audio_lab/AudioConversionProfileEditor.qml", "category": "tools", "status": "functional"},
    "audio_lab_job_detail": {"title": "Detalle de trabajo", "source": "../pages/audio_lab/AudioJobDetail.qml", "category": "detail", "status": "functional", "params": {"job": {"required": True, "type": "object"}}},
    "metadata.inspector": {"title": "Inspector de metadatos", "source": "../pages/metadata/MetadataInspectorPage.qml", "category": "tools", "status": "functional"},
    "metadata.batch": {"title": "Edicin por lotes", "source": "../pages/metadata/MetadataBatchEditor.qml", "category": "tools", "status": "functional"},
    "tagging": {"title": "Smart Tagging", "source": "../pages/SmartTaggingPage.qml", "category": "tools", "status": "functional"},
    "library_doctor": {"title": "Library Doctor", "source": "../pages/LibraryDoctorPage.qml", "category": "tools", "status": "functional"},
    "equalizer": {"title": "Ecualizador", "source": "../pages/EqPage.qml", "category": "tools", "status": "functional"},
    "outputs": {"title": "Perfiles de salida", "source": "../pages/OutputProfilesPage.qml", "category": "settings", "status": "functional"},
    "devices.list": {"title": "Dispositivos", "source": "../pages/DevicesPage.qml", "category": "core", "status": "functional"},
    "devices.detail": {"title": "Dispositivo", "source": "../pages/devices/DeviceDetailPage.qml", "category": "detail", "status": "functional", "params": {"device_id": {"required": True, "type": "string"}}},
    "devices.pairing": {"title": "Vincular dispositivo", "source": "../pages/devices/DevicePairingPage.qml", "category": "detail", "status": "functional"},
    "connections": {"title": "Conexiones", "source": "../pages/connections/ConnectionsPage.qml", "category": "core", "status": "functional"},
    "connections.detail": {"title": "Conexin", "source": "../pages/connections/ConnectionDetailPage.qml", "category": "detail", "status": "functional", "params": {"connection_id": {"required": True, "type": "string"}}},
    "home_audio": {"title": "Home Audio", "source": "../pages/home_audio/HomeAudioPage.qml", "category": "core", "status": "functional"},
    "settings.general": {"title": "Ajustes generales", "source": "../pages/settings/SettingsGeneralPage.qml", "category": "settings", "status": "functional"},
    "settings.appearance": {"title": "Apariencia", "source": "../pages/settings/SettingsAppearancePage.qml", "category": "settings", "status": "functional"},
    "settings.playback": {"title": "Reproduccin", "source": "../pages/settings/SettingsPlaybackPage.qml", "category": "settings", "status": "functional"},
    "settings.library": {"title": "Biblioteca", "source": "../pages/settings/SettingsLibraryPage.qml", "category": "settings", "status": "functional"},
    "settings.accessibility": {"title": "Accesibilidad", "source": "../pages/settings/SettingsAccessibilityPage.qml", "category": "settings", "status": "functional"},
    "settings.audio": {"title": "Audio", "source": "../pages/settings/SettingsAudioPage.qml", "category": "settings", "status": "functional"},
    "settings.about": {"title": "Acerca de", "source": "../pages/settings/SettingsAboutPage.qml", "category": "settings", "status": "functional"},
    "diagnostics": {"title": "Diagnstico", "source": "../pages/DiagnosticsPage.qml", "category": "system", "status": "functional"},
    "diagnostics.bitperfect": {"title": "Monitor Bit-Perfect", "source": "../pages/DiagnosticsPage.qml", "category": "system", "status": "functional"},
    "diagnostics.identifier": {"title": "Identificador de msica", "source": "../pages/DiagnosticsPage.qml", "category": "system", "status": "functional"},
    "discover": {"title": "Descubrir", "source": "../pages/library/GenresPage.qml", "category": "library", "status": "functional"},
    "ecosystem": {"title": "Ecosistema Michi", "source": "../pages/home/EcosystemCard.qml", "category": "core", "status": "functional"},
    "ai": {"title": "Michi AI", "source": "../pages/assistant/AssistantPage.qml", "category": "core", "status": "functional"},
    "assistant": {"title": "Michi AI", "source": "../pages/assistant/AssistantPage.qml", "category": "core", "status": "functional"},
    "disc_lab": {"title": "Disc Lab", "source": "../pages/DiscLabPage.qml", "category": "tools", "status": "experimental"},
    "audio_lab": {"title": "Audio Lab", "source": "../pages/audio_lab/AudioLabOverviewPage.qml", "category": "tools", "status": "functional"},
    "playback": {"title": "Reproduccin", "source": "../pages/PlaybackPage.qml", "category": "core", "status": "functional"},
    "library": {"title": "Biblioteca", "source": "../pages/library/LibraryPage.qml", "category": "core", "status": "functional"},
    "settings": {"title": "Ajustes", "source": "../pages/SettingsPage.qml", "category": "settings", "status": "functional"},
    "placeholder": {"title": "Seccin en migracin", "source": "../pages/PlaceholderPage.qml", "category": "system", "status": "placeholder"},
}

CAPABILITY_MAP: dict[str, str] = {
    "audio_lab.*": "audio_lab",
    "metadata.*": "metadata",
    "tagging": "smart_tagging",
    "library_doctor": "library_doctor",
    "equalizer": "eq",
    "outputs": "output_profiles",
    "devices.*": "devices",
    "connections.*": "connections",
    "home_audio": "home_audio",
    "settings.*": "settings",
    "diagnostics": "diagnostics",
    "ai": "ai",
    "disc_lab": "disc_lab",
}
