"""RouteRegistry — single source of truth for QML routes."""
ROUTES: dict[str, dict] = {
    "home": {"title": "Inicio", "source": "../pages/home/HomePage.qml", "category": "core", "status": "functional"},
    "library": {"title": "Biblioteca", "source": "../pages/library/LibraryPage.qml", "category": "core", "status": "functional"},
    "playback": {"title": "Reproducción", "source": "../pages/PlaybackPage.qml", "category": "core", "status": "functional"},
    "connections": {"title": "Conexiones", "source": "../pages/connections/ConnectionsPage.qml", "category": "core", "status": "functional"},
    "home_audio": {"title": "Home Audio", "source": "../pages/home_audio/HomeAudioPage.qml", "category": "core", "status": "experimental"},
    "assistant": {"title": "Michi AI", "source": "../pages/assistant/AssistantPage.qml", "category": "core", "status": "functional"},
    "audio_lab": {"title": "Audio Lab", "source": "../pages/assistant/AudioLabPage.qml", "category": "tools", "status": "functional"},
    "radio": {"title": "Radio", "source": "../pages/RadioPage.qml", "category": "core", "status": "functional"},
    "playlists": {"title": "Playlists", "source": "../pages/playlists/PlaylistsPage.qml", "category": "core", "status": "functional"},
    "playlist_detail": {"title": "Playlist", "source": "../pages/playlists/PlaylistDetailPage.qml", "category": "detail", "status": "functional"},
    "metadata_inspector": {"title": "Inspector de metadatos", "source": "../pages/metadata/MetadataInspectorPage.qml", "category": "tools", "status": "functional"},
    "settings": {"title": "Ajustes", "source": "../pages/SettingsPage.qml", "category": "core", "status": "functional"},
    "devices": {"title": "Dispositivos", "source": "../pages/DevicesPage.qml", "category": "core", "status": "functional"},
    "eq": {"title": "Ecualizador", "source": "../pages/EqPage.qml", "category": "tools", "status": "functional"},
    "library_doctor": {"title": "Library Doctor", "source": "../pages/LibraryDoctorPage.qml", "category": "tools", "status": "functional"},
    "disc_lab": {"title": "Disc Lab", "source": "../pages/DiscLabPage.qml", "category": "tools", "status": "experimental"},
    "output_profiles": {"title": "Perfiles de salida", "source": "../pages/OutputProfilesPage.qml", "category": "settings", "status": "functional"},
    "smart_tagging": {"title": "Smart Tagging", "source": "../pages/SmartTaggingPage.qml", "category": "tools", "status": "functional"},
    "mix": {"title": "Mix", "source": "../pages/MixHubPage.qml", "category": "core", "status": "experimental"},
    "mix_detail": {"title": "Mix", "source": "../pages/MixDetailPage.qml", "category": "detail", "status": "experimental"},
    "diagnostics": {"title": "Diagnóstico", "source": "../pages/DiagnosticsPage.qml", "category": "system", "status": "experimental"},
    "lyrics": {"title": "Letra", "source": "../pages/LyricsPage.qml", "category": "tools", "status": "functional"},
    "album_detail": {"title": "Álbum", "source": "../pages/library/AlbumDetailPage.qml", "category": "detail", "status": "functional", "params": {"album_key": {"required": True, "type": "string"}}},
    "artist_detail": {"title": "Artista", "source": "../pages/library/ArtistDetailPage.qml", "category": "detail", "status": "functional", "params": {"artist": {"required": True, "type": "string"}}},
    "queue": {"title": "Cola", "source": "../pages/queue/QueuePage.qml", "category": "core", "status": "new"},
    "history": {"title": "Historial", "source": "../pages/history/HistoryPage.qml", "category": "core", "status": "new"},
    "jobs": {"title": "Trabajos", "source": "../pages/jobs/JobsPage.qml", "category": "core", "status": "new"},
    "library_sources": {"title": "Fuentes de biblioteca", "source": "../pages/settings/LibrarySourcesPage.qml", "category": "settings", "status": "functional"},
    "placeholder": {"title": "Sección en migración", "source": "../pages/PlaceholderPage.qml", "category": "system", "status": "placeholder"},
    "library/tracks": {"title": "Canciones", "source": "../pages/library/tracks/TracksPage.qml", "category": "library", "status": "functional"},
    "library/albums": {"title": "Álbumes", "source": "../pages/library/AlbumGridPage.qml", "category": "library", "status": "functional"},
    "library/albums/:albumId": {"title": "Álbum", "source": "../pages/library/AlbumDetailPage.qml", "category": "detail", "status": "functional", "params": {"albumId": {"required": True, "type": "string"}}},
    "library/artists": {"title": "Artistas", "source": "../pages/library/ArtistGridPage.qml", "category": "library", "status": "functional"},
    "library/artists/:artistId": {"title": "Artista", "source": "../pages/library/ArtistDetailPage.qml", "category": "detail", "status": "functional", "params": {"artistId": {"required": True, "type": "string"}}},
    "library/folders": {"title": "Carpetas", "source": "../pages/library/FolderBrowserPage.qml", "category": "library", "status": "functional"},
    "library/folders/:folderId": {"title": "Carpeta", "source": "../pages/library/FolderBrowserPage.qml", "category": "detail", "status": "functional", "params": {"folderId": {"required": True, "type": "string"}}},
    "library/sources": {"title": "Fuentes", "source": "../pages/library/SourcesPage.qml", "category": "library", "status": "functional"},
    "library/genres": {"title": "Géneros", "source": "../pages/library/GenresPage.qml", "category": "library", "status": "functional"},
    "library/genres/:genre": {"title": "Género", "source": "../pages/library/GenreDetailPage.qml", "category": "detail", "status": "functional", "params": {"genre": {"required": True, "type": "string"}}},
    "library/composers": {"title": "Compositores", "source": "../pages/library/ComposersPage.qml", "category": "library", "status": "functional"},
    "library/composers/:composer": {"title": "Compositor", "source": "../pages/library/ComposerDetailPage.qml", "category": "detail", "status": "functional", "params": {"composer": {"required": True, "type": "string"}}},
    "library/years": {"title": "Años", "source": "../pages/library/YearsPage.qml", "category": "library", "status": "functional"},
    "library/recent": {"title": "Recientes", "source": "../pages/library/RecentPage.qml", "category": "library", "status": "functional"},
    "library/favorites": {"title": "Favoritos", "source": "../pages/library/FavoritesPage.qml", "category": "library", "status": "functional"},
    "library/unplayed": {"title": "No reproducidos", "source": "../pages/library/UnplayedPage.qml", "category": "library", "status": "functional"},
    "library/most-played": {"title": "Más reproducidos", "source": "../pages/library/MostPlayedPage.qml", "category": "library", "status": "functional"},
    "library/missing": {"title": "Archivos faltantes", "source": "../pages/library/MissingPage.qml", "category": "library", "status": "functional"},
}
