from __future__ import annotations

from typing import Any, Protocol


class ActionRegistryProtocol(Protocol):
    def register(self, name: str, spec: dict[str, Any]) -> None: ...
    def resolve(self, name: str) -> dict[str, Any] | None: ...
    def list_actions(self) -> list[str]: ...
    def has(self, name: str) -> bool: ...
