from __future__ import annotations

from typing import Any, Protocol


class AudioLabServiceProtocol(Protocol):
    def setup(self) -> None: ...
    def capability_map(self) -> dict[str, bool]: ...
    def status(self) -> dict[str, Any]: ...
    @property
    def probe(self) -> Any: ...
    @property
    def analysis(self) -> Any: ...
    @property
    def conversion(self) -> Any: ...
    @property
    def integrity(self) -> Any: ...
