from __future__ import annotations

from typing import Any, Protocol


class ConfirmationServiceProtocol(Protocol):
    def request(self, operation_id: str, target: str, description: str = "", field_count: int = 0, requires_backup: bool = True) -> Any: ...
    def approve(self, token: str) -> Any | None: ...
    def reject(self, token: str) -> bool: ...
    def revoke(self, operation_id: str) -> None: ...
    def cleanup_expired(self) -> None: ...
    def shutdown(self) -> None: ...
