from __future__ import annotations

from typing import Any, Protocol


class DeviceSyncServiceProtocol(Protocol):
    def discover(self) -> list[dict[str, Any]]: ...
    def pair(self, identity: dict[str, Any]) -> dict[str, Any]: ...
    def unpair(self, key: str) -> dict[str, Any]: ...
    def get_paired(self) -> list[dict[str, Any]]: ...
    def list_jobs(self) -> list[dict[str, Any]]: ...
    def get_job(self, job_id: str) -> Any | None: ...
    def execute_job(self, job_id: str) -> dict[str, Any]: ...
    def cancel_job(self, job_id: str) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...
