from __future__ import annotations

from typing import Any, Protocol


class JobServiceProtocol(Protocol):
    def submit(self, job_type: str, payload: dict[str, Any]) -> str: ...
    def cancel(self, job_id: str) -> bool: ...
    def status(self, job_id: str) -> dict[str, Any]: ...
    def list_active(self) -> list[dict[str, Any]]: ...
    def list_by_type(self, job_type: str) -> list[dict[str, Any]]: ...
