from __future__ import annotations

from typing import Any, Protocol


class MichiAIServiceProtocol(Protocol):
    def process_message(self, message: str, context: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def cancel(self) -> None: ...
    def is_processing(self) -> bool: ...
    def get_suggestions(self, context: dict[str, Any]) -> list[dict[str, Any]]: ...
