from __future__ import annotations

from typing import Any, Protocol


class MixServiceProtocol(Protocol):
    def fetch_tracks(self, sql: str, params: list, limit: int = 50) -> list[dict[str, Any]]: ...
    def favorites(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def recent(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def most_played(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def unplayed(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def genre(self, genre: str, limit: int = 50) -> list[dict[str, Any]]: ...
