from __future__ import annotations

from typing import Any, Protocol


class NavigationProtocol(Protocol):
    def navigate(self, route: str) -> dict[str, Any]: ...
    def can_navigate(self, route: str) -> bool: ...
    def current_route(self) -> str: ...
    def list_routes(self) -> list[str]: ...
    def back(self) -> dict[str, Any]: ...
    def forward(self) -> dict[str, Any]: ...
