from __future__ import annotations

from typing import Any, Callable, Protocol


class NotificationServiceProtocol(Protocol):
    def notify(self, notification: Any) -> Any: ...
    def update(self, notification_id: str, **kwargs) -> Any | None: ...
    def dismiss(self, notification_id: str) -> bool: ...
    def get(self, notification_id: str) -> Any | None: ...
    def list_all(self) -> list[Any]: ...
    def clear(self) -> None: ...
    def on(self, listener: Callable) -> None: ...
    def off(self, listener: Callable) -> None: ...
