from __future__ import annotations

from typing import Any, Protocol


class PlaybackServiceProtocol(Protocol):
    def play(self, filepath: str, title: str = "", artist: str = "") -> dict[str, Any]: ...
    def pause(self) -> dict[str, Any]: ...
    def toggle(self) -> dict[str, Any]: ...
    def stop(self) -> dict[str, Any]: ...
    def seek(self, seconds: float) -> dict[str, Any]: ...
    def set_volume(self, vol: int) -> dict[str, Any]: ...
    def play_next(self) -> dict[str, Any]: ...
    def play_prev(self) -> dict[str, Any]: ...
    @property
    def state(self) -> str: ...
    @property
    def current(self) -> str: ...
