from __future__ import annotations

from typing import Any, Callable, Protocol


class QueueServiceProtocol(Protocol):
    """Structural contract for canonical queue consumers."""

    @property
    def items(self) -> list[dict[str, Any]]: ...
    @property
    def count(self) -> int: ...
    @property
    def current_index(self) -> int: ...
    @property
    def repeat(self) -> str: ...
    @property
    def shuffle(self) -> bool: ...
    @property
    def revision(self) -> int: ...
    @property
    def can_undo(self) -> bool: ...
    def get_items(self) -> list[dict[str, Any]]: ...
    def get_state(self) -> dict[str, Any]: ...
    def subscribe(self, callback: Callable[[str, dict], None]
                  ) -> Callable[[], None]: ...
    def replace(self, items: list[dict[str, Any]],
                start_index: int | None = None) -> dict[str, Any]: ...
    def replace_and_play(self, items: list[dict[str, Any]],
                         start_index: int = 0) -> dict[str, Any]: ...
    def append(self, items: list[dict[str, Any]]) -> dict[str, Any]: ...
    def insert_next(self, items: Any) -> dict[str, Any]: ...
    def clear(self) -> dict[str, Any]: ...
    def reorder(self, from_index: int, to_index: int) -> dict[str, Any]: ...
    def remove(self, indices: list[int]) -> dict[str, Any]: ...
    def enqueue(self, items: Any, play_now: bool = False) -> dict[str, Any]: ...
    def enqueue_next(self, items: Any) -> dict[str, Any]: ...
    def play_from_index(self, index: int) -> dict[str, Any]: ...
    def next(self) -> dict[str, Any]: ...
    def previous(self) -> dict[str, Any]: ...
    def reconcile_backend_progress(self, index: int, filepath: str, reason: str,
                                   revision: int | None = None
                                   ) -> dict[str, Any]: ...
    def set_repeat(self, mode: str) -> dict[str, Any]: ...
    def toggle_repeat(self) -> dict[str, Any]: ...
    def set_shuffle(self, enabled: bool) -> dict[str, Any]: ...
    def toggle_shuffle(self) -> dict[str, Any]: ...
    def undo(self) -> dict[str, Any]: ...
    def save_state(self, position: float = 0.0) -> dict[str, Any]: ...
    def load_state(self, resolve_fn: Callable[[dict], dict | None] | None = None
                   ) -> dict[str, Any]: ...
    def shutdown(self, position: float = 0.0) -> None: ...
