from __future__ import annotations

from typing import Any, Protocol


class QueueServiceProtocol(Protocol):
    def get_items(self) -> list[dict[str, Any]]: ...
    def set_items(self, items: list[dict[str, Any]]) -> None: ...
    def insert(self, index: int, items: list[dict[str, Any]]) -> None: ...
    def append(self, items: list[dict[str, Any]]) -> None: ...
    def replace(self, items: list[dict[str, Any]]) -> None: ...
    def clear(self) -> None: ...
    def reorder(self, from_index: int, to_index: int) -> None: ...
    def remove(self, indices: list[int]) -> None: ...
    def undo(self) -> None: ...
    def shutdown(self) -> None: ...
