from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PlaybackGateway(Protocol):
    def play_track(self, track_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def play_album(self, album_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def play_artist(self, artist_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def play_playlist(self, playlist_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def pause(self, **kwargs: Any) -> dict[str, Any]: ...
    def resume(self, **kwargs: Any) -> dict[str, Any]: ...
    def stop(self, **kwargs: Any) -> dict[str, Any]: ...
    def next(self, **kwargs: Any) -> dict[str, Any]: ...
    def previous(self, **kwargs: Any) -> dict[str, Any]: ...
    def seek(self, position_seconds: float, **kwargs: Any) -> dict[str, Any]: ...
    def set_volume(self, volume: float, **kwargs: Any) -> dict[str, Any]: ...
    def set_repeat(self, mode: str, **kwargs: Any) -> dict[str, Any]: ...
    def set_shuffle(self, enabled: bool, **kwargs: Any) -> dict[str, Any]: ...
    def get_state(self) -> dict[str, Any]: ...


@runtime_checkable
class QueueGateway(Protocol):
    def get_queue(self) -> dict[str, Any]: ...
    def add_to_queue(self, track_ids: list[str], **kwargs: Any) -> dict[str, Any]: ...
    def play_next(self, track_ids: list[str], **kwargs: Any) -> dict[str, Any]: ...
    def replace_queue(self, track_ids: list[str], **kwargs: Any) -> dict[str, Any]: ...
    def remove_from_queue(self, position: int, **kwargs: Any) -> dict[str, Any]: ...
    def clear_queue(self, **kwargs: Any) -> dict[str, Any]: ...
    def reorder_queue(self, from_pos: int, to_pos: int, **kwargs: Any) -> dict[str, Any]: ...


@runtime_checkable
class LibraryGateway(Protocol):
    def search(self, query: str, **filters: Any) -> dict[str, Any]: ...
    def get_track(self, track_id: str) -> dict[str, Any]: ...
    def get_album(self, album_id: str) -> dict[str, Any]: ...
    def get_artist(self, artist_id: str) -> dict[str, Any]: ...
    def list_recent(self, limit: int = 20) -> dict[str, Any]: ...
    def list_unplayed(self, limit: int = 20) -> dict[str, Any]: ...
    def list_favorites(self, limit: int = 20) -> dict[str, Any]: ...
    def find_metadata_gaps(self) -> dict[str, Any]: ...


@runtime_checkable
class PlaylistGateway(Protocol):
    def list_playlists(self) -> dict[str, Any]: ...
    def get_playlist(self, playlist_id: str) -> dict[str, Any]: ...
    def create_playlist(self, name: str, track_ids: list[str] | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def add_to_playlist(self, playlist_id: str, track_ids: list[str], **kwargs: Any) -> dict[str, Any]: ...
    def remove_from_playlist(self, playlist_id: str, position: int, **kwargs: Any) -> dict[str, Any]: ...
    def reorder_playlist(self, playlist_id: str, from_pos: int, to_pos: int, **kwargs: Any) -> dict[str, Any]: ...


@runtime_checkable
class AudioLabGateway(Protocol):
    def probe_audio(self, track_id: str) -> dict[str, Any]: ...
    def analyze_audio(self, track_ids: list[str]) -> dict[str, Any]: ...
    def recommend_conversion(self, track_ids: list[str], target_format: str, **kwargs: Any) -> dict[str, Any]: ...
    def preview_conversion(self, plan_id: str) -> dict[str, Any]: ...
    def start_conversion(self, plan_id: str) -> dict[str, Any]: ...
    def cancel_conversion(self, job_id: str) -> dict[str, Any]: ...
    def analyze_replaygain(self, track_ids: list[str]) -> dict[str, Any]: ...
    def check_integrity(self, track_ids: list[str]) -> dict[str, Any]: ...
    def compare_audio(self, track_id_a: str, track_id_b: str) -> dict[str, Any]: ...
    def get_status(self) -> dict[str, Any]: ...


@runtime_checkable
class DeviceGateway(Protocol):
    def list_devices(self) -> dict[str, Any]: ...
    def diagnose_ecosystem(self) -> dict[str, Any]: ...
    def diagnose_server(self) -> dict[str, Any]: ...
    def diagnose_home_audio(self) -> dict[str, Any]: ...
    def diagnose_pairing(self) -> dict[str, Any]: ...
    def plan_sync(self, playlist_id: str, device_id: str) -> dict[str, Any]: ...
    def start_sync(self, plan_id: str) -> dict[str, Any]: ...
    def cancel_sync(self, job_id: str) -> dict[str, Any]: ...


@runtime_checkable
class SettingsGateway(Protocol):
    def get_setting(self, key: str) -> dict[str, Any]: ...
    def suggest_change(self, key: str, value: Any) -> dict[str, Any]: ...
    def preview_change(self, key: str, value: Any) -> dict[str, Any]: ...
    def apply_change(self, key: str, value: Any) -> dict[str, Any]: ...
    def list_settings(self) -> dict[str, Any]: ...


@runtime_checkable
class DiagnosticsGateway(Protocol):
    def get_diagnostics(self) -> dict[str, Any]: ...
    def get_audio_diagnostics(self) -> dict[str, Any]: ...
    def get_network_diagnostics(self) -> dict[str, Any]: ...


@runtime_checkable
class NavigationRequestGateway(Protocol):
    def request_navigation(self, target: str, params: dict[str, Any] | None = None) -> dict[str, Any]: ...


@runtime_checkable
class JobGateway(Protocol):
    def list_jobs(self) -> dict[str, Any]: ...
    def cancel_job(self, job_id: str) -> dict[str, Any]: ...
    def get_job_status(self, job_id: str) -> dict[str, Any]: ...


@runtime_checkable
class MixGateway(Protocol):
    def create_mix(self, strategy: str, **params: Any) -> dict[str, Any]: ...
    def explain_mix(self, mix_id: str) -> dict[str, Any]: ...
    def save_mix_as_playlist(self, mix_id: str, name: str) -> dict[str, Any]: ...
    def cancel_mix(self, job_id: str) -> dict[str, Any]: ...


@runtime_checkable
class RadioGateway(Protocol):
    def search_stations(self, query: str) -> dict[str, Any]: ...
    def list_favorites(self) -> dict[str, Any]: ...
    def play_station(self, station_id: str) -> dict[str, Any]: ...
    def stop_radio(self) -> dict[str, Any]: ...
    def probe_station(self, url: str) -> dict[str, Any]: ...


@runtime_checkable
class LyricsGateway(Protocol):
    def get_current_lyrics(self) -> dict[str, Any]: ...
    def search_lyrics(self, title: str, artist: str) -> dict[str, Any]: ...
    def refresh_lyrics(self, track_id: str) -> dict[str, Any]: ...


@runtime_checkable
class MetadataGateway(Protocol):
    def inspect_metadata(self, track_id: str) -> dict[str, Any]: ...
    def build_proposal(self, track_id: str, fields: list[str] | None = None) -> dict[str, Any]: ...
    def preview_changes(self, proposal_id: str) -> dict[str, Any]: ...
    def apply_review(self, review_id: str) -> dict[str, Any]: ...
    def rollback(self, review_id: str) -> dict[str, Any]: ...


@runtime_checkable
class LibraryDoctorGateway(Protocol):
    def scan(self) -> dict[str, Any]: ...
    def preview_repair(self, scan_id: str) -> dict[str, Any]: ...
    def apply_repair(self, repair_id: str) -> dict[str, Any]: ...
    def cancel_repair(self, job_id: str) -> dict[str, Any]: ...


@runtime_checkable
class ConnectionsGateway(Protocol):
    def list_connections(self) -> dict[str, Any]: ...
    def diagnose(self) -> dict[str, Any]: ...
    def preview_change(self, connection_id: str, config: dict[str, Any]) -> dict[str, Any]: ...
    def apply_change(self, connection_id: str, config: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class HomeAudioGateway(Protocol):
    def get_status(self) -> dict[str, Any]: ...
    def get_zones(self) -> dict[str, Any]: ...
    def set_zone_volume(self, zone_id: str, volume: int) -> dict[str, Any]: ...
    def diagnose(self) -> dict[str, Any]: ...
